In [5]:
from sklearn.cluster import DBSCAN
from shapely.geometry import MultiPoint
import pandas as pd
import datetime
from dateutil import parser
import numpy as np
import geopandas as gpd
from dateutil import parser


In [12]:
datafile='C:\File\GISFile.csv'



In [13]:
data=pd.read_csv(datafile)

In [20]:
 data.Date=[parser.parse(t).date() for t in data.Date]

In [35]:
data

lon        lat PATIENT_IDENTIFIER        Date              x  \
0    -81.624544  41.469299          E37730375  2020-04-29  447849.087885   
1    -81.807257  41.479861           E5377021  2020-05-17  432602.947500   
2    -81.527352  41.535256       E14038723116  2020-06-25  456009.544502   
3    -81.860125  41.467062       E15040036023  2020-05-05  428174.884570   
4    -81.578029  41.139601       E14042127130  2020-04-07  451489.478252   
5    -82.045827  41.462269           E4810254  2020-03-25  412661.129149   
6    -81.994647  41.387349       E14039728058  2020-03-23  416839.772009   
7    -80.258361  25.947707       E14041383766  2020-06-06  574255.619703   
8    -82.161045  41.472538          E37471583  2020-04-14  403054.213072   
9    -80.203205  25.770398       E14044978365  2020-06-25  579897.368939   
10   -81.556368  41.126187           E5749817  2020-03-31  453297.852309   
11   -81.737685  41.470294       E14041968439  2020-06-29  438402.426436   
12   -81.527124  41.386690           E5821141  2020-06-18  455928.090859   
13   -80.337792  25.951486       E14044983773  2020-06-27  566300.346354   
14   -81.494205  41.572117           E5812118  2020-07-11  458798.012279   
15   -80.206560  25.986968       E14044664881  2020-05-01  579415.958524   
16   -81.786954  41.139394           E5169292  2020-05-12  433955.312625   
17   -80.857348  41.880190       E14041160522  2020-04-22  511836.235975   
18   -81.442054  41.414802           E5128436  2020-05-16  463056.587712   
19   -81.583997  41.441811       E13040022902  2020-05-27  451214.280809   
20   -80.184065  26.033938       E14044641570  2020-04-04  581635.102906   
21   -82.071633  41.399755           E5562712  2020-04-11  410420.086504   
22   -81.774870  41.453698       E14039354508  2020-05-17  435280.912022   
23   -81.732217  41.439384       E14039573282  2020-05-30  438829.979419   
24   -81.936256  41.429171       E14039560574  2020-03-28  421771.958207   
25   -81.591107  41.441674       E14038708373  2020-06-02  450620.221837   
26   -81.597708  41.481476          E37653928  2020-05-03  450099.308829   
27   -81.533441  41.600232       E14043368192  2020-06-02  455546.176211   
28   -81.923619  41.137433           E5350390  2020-04-22  422483.342193   
29   -80.077804  26.461443       E14044687102  2020-06-02  591930.088587   
...         ...        ...                ...         ...            ...   
1969 -81.685663  40.944366       E14040628815  2020-03-31  442286.034206   
1970 -81.505375  41.587710           E5653930  2020-05-06  457876.897966   
1971 -81.352309  41.496602           E5206199  2020-05-08  470593.754903   
1972 -81.482953  40.521333       E14044017949  2020-05-12  459090.419045   
1973 -81.413952  41.342365       E13039953778  2020-06-03  465366.731451   
1974 -81.693665  41.431888       E15040246484  2020-05-01  442043.998250   
1975 -81.782993  41.445903       E14039085852  2020-06-17  434594.624290   
1976 -81.545069  41.536436           E6040107  2020-06-30  454532.455334   
1977 -81.627493  41.517314           E4985092  2020-03-29  447641.518315   
1978 -80.381280  25.999663       E14041862918  2020-04-22  561920.977399   
1979 -81.507019  41.048139       E14042518333  2020-04-17  457389.887553   
1980 -81.537466  41.442954          E37834257  2020-06-18  455102.172638   
1981 -81.797565  41.433627       E14041467873  2020-06-24  433364.821967   
1982 -82.053923  41.448115       E14040962767  2020-05-14  411965.870191   
1983 -81.514454  41.530184       E14038967065  2020-03-21  457082.116274   
1984 -82.119904  41.388268       E14042985516  2020-06-05  406368.469981   
1985 -81.549157  41.411300       E14039852816  2020-04-09  454103.261136   
1986 -81.692330  41.499448          E37715810  2020-05-16  442215.555288   
1987 -80.585183  41.627584       E14043649328  2020-06-02  534553.775321   
1988 -81.709164  41.453485       E14039168910  2020-05-28  440768.685164   
1989 -80.099994  26.341408       E14044658959  2020-04-23  5

In [23]:
start_date=None

In [24]:
  if start_date is None:
        start_date=np.min(data.Date.values)

In [29]:
recheader=['id','centroid_x','centroid_y']

In [25]:
start_date

datetime.date(2020, 1, 7)

In [26]:
end_date=datetime.datetime.now().date()

In [27]:
 datevals=[start_date+datetime.timedelta(days=i) for i in range((end_date-start_date).days+1)]

In [30]:
  recheader.extend(datevals)

In [31]:
 gpframe=gpd.GeoDataFrame(data,geometry=gpd.points_from_xy(data.lon, data.lat))

In [32]:
gpframe.crs={'init': 'epsg:4326'}
gpframe=gpframe.to_crs({'init': 'epsg:26917'})
data['x']=[geom.x for geom in gpframe.geometry]
data['y']=[geom.y for geom in gpframe.geometry]

In [34]:
data=data.drop(columns=['geometry'])


In [36]:

    xy=data[['x','y']].values
  

In [37]:
xy


array([[ 447849.08788542, 4591044.05954433],
       [ 432602.94750043, 4592342.90169444],
       [ 456009.54450162, 4598312.56492716],
       ...,
       [ 455400.30244077, 4521919.84295097],
       [ 592802.50690859, 2937230.42149944],
       [ 436044.74097307, 4575752.3308105 ]])

In [38]:

    latlon=data[['lon','lat']].values


In [39]:
latlon

array([[-81.624544,  41.469299],
       [-81.807257,  41.479861],
       [-81.527352,  41.535256],
       ...,
       [-81.529086,  40.847111],
       [-80.068317,  26.55269 ],
       [-81.764283,  41.330715]])

In [40]:

    dates=data['Date'].values

In [41]:
dates

array([datetime.date(2020, 4, 29), datetime.date(2020, 5, 17),
       datetime.date(2020, 6, 25), ..., datetime.date(2020, 3, 26),
       datetime.date(2020, 4, 19), datetime.date(2020, 5, 25)],
      dtype=object)

In [42]:
 clusterData=pd.DataFrame(columns=recheader)

In [43]:
  clustering = DBSCAN(eps=100, min_samples=2,algorithm='kd_tree').fit(xy)

In [44]:
labels = clustering.labels_
total_clusters = len(set(labels))
k=0
geometries=[]
ids=[]

In [45]:
labels

array([-1, -1, -1, ..., -1, -1, 36], dtype=int64)

In [46]:
total_clusters

176

In [46]:
for i in range(total_clusters):
        ltln=latlon[labels==i]
        date=dates[labels==i]
        prjpoints=xy[labels==i]
        if len(ltln)!=0 and len(ltln)>=minneighbors:
            tdframe=pd.DataFrame(columns=['date'])
            tdframe.date=datevals
            newdframe=pd.DataFrame(columns=['date','counts'])
            #aggregate counts based on date
            unique, counts = np.unique(Date, return_counts=True)
            newdframe.date=unique
            newdframe.counts=counts
            tdframe=tdframe.merge(newdframe,on='Date',how='outer')
            tdframe=tdframe.fillna(0)
            #cumulative sum for the dates
            cnts=np.cumsum(tdframe.counts.values)
            #set zero for total neighbors
            cnts[cnts<minneighbors]=0
            tdframe.counts=cnts
            #for generating centroids
            geom=MultiPoint(ltln)
            dat=[k,geom.centroid.x,geom.centroid.y]
            ids.append(k)
            geom_proj=MultiPoint(prjpoints)
            #convex hulls based on all members
            geom_hull=geom_proj.convex_hull
            if geom_hull.geom_type!='Polygon':
                geom_hull=geom_hull.buffer(maxdistance)
            geometries.append(geom_hull)
            dat.extend(tdframe.counts.values.tolist())
            clusterData.loc[len(clusterData)]=dat
            k+=1

NameError: name 'Date' is not defined

In [41]:
minneighbors=2

In [47]:
for i in range(total_clusters):
        ltln=latlon[labels==i]
        date=dates[labels==i]
        prjpoints=xy[labels==i]

In [48]:
if len(ltln)!=0 and len(ltln)>=minneighbors:
            tdframe=pd.DataFrame(columns=['date'])
            tdframe.date=datevals
            newdframe=pd.DataFrame(columns=['date','counts'])

In [52]:
unique, counts = np.unique(date, return_counts=True)
newdframe.date=unique
newdframe.counts=counts
tdframe=tdframe.merge(newdframe,on='date',how='outer')

In [53]:
tdframe=tdframe.fillna(0)

In [54]:
tdframe

date  counts
0    2019-04-06     0.0
1    2019-04-07     0.0
2    2019-04-08     0.0
3    2019-04-09     0.0
4    2019-04-10     0.0
5    2019-04-11     0.0
6    2019-04-12     0.0
7    2019-04-13     0.0
8    2019-04-14     0.0
9    2019-04-15     0.0
10   2019-04-16     0.0
11   2019-04-17     0.0
12   2019-04-18     0.0
13   2019-04-19     0.0
14   2019-04-20     0.0
15   2019-04-21     0.0
16   2019-04-22     0.0
17   2019-04-23     0.0
18   2019-04-24     0.0
19   2019-04-25     0.0
20   2019-04-26     0.0
21   2019-04-27     0.0
22   2019-04-28     0.0
23   2019-04-29     0.0
24   2019-04-30     0.0
25   2019-05-01     0.0
26   2019-05-02     0.0
27   2019-05-03     0.0
28   2019-05-04     0.0
29   2019-05-05     0.0
..          ...     ...
438  2020-06-17     0.0
439  2020-06-18     0.0
440  2020-06-19     0.0
441  2020-06-20     0.0
442  2020-06-21     0.0
443  2020-06-22     0.0
444  2020-06-23     0.0
445  2020-06-24     0.0
446  2020-06-25     0.0
447  2020-06-26     0.0
448  2020-06-27     0.0
449  2020-06-28     0.0
450  2020-06-29     0.0
451  2020-06-30     0.0
452  2020-07-01     0.0
453  2020-07-02     0.0
454  2020-07-03     0.0
455  2020-07-04     0.0
456  2020-07-05     0.0
457  2020-07-06     0.0
458  2020-07-07     0.0
459  2020-07-08     0.0
460  2020-07-09     0.0
461  2020-07-10     0.0
462  2020-07-11     0.0
463  2020-07-12     0.0
464  2020-07-13     0.0
465  2020-07-14     0.0
466  2020-07-15     0.0
467  2020-07-16     0.0

[468 rows x 2 columns]

In [60]:
cnts=0
    

In [61]:
tdframe.counts=cnts

In [63]:
geom=MultiPoint(ltln)
           

In [64]:
geom

In [66]:

            dat=[k,geom.centroid.x,geom.centroid.y]
          

IndexError: list index out of range