In [5]:
from sklearn.cluster import DBSCAN
from shapely.geometry import MultiPoint
import pandas as pd
import datetime
from dateutil import parser
import numpy as np
import geopandas as gpd
from dateutil import parser


In [12]:
datafile='C:\File\GISFile.csv'



In [13]:
data=pd.read_csv(datafile)

In [20]:
 data.Date=[parser.parse(t).date() for t in data.Date]

In [23]:
start_date=None

In [24]:
  if start_date is None:
        start_date=np.min(data.Date.values)

In [29]:
recheader=['id','centroid_x','centroid_y']

In [25]:
start_date

datetime.date(2020, 1, 7)

In [26]:
end_date=datetime.datetime.now().date()

In [27]:
 datevals=[start_date+datetime.timedelta(days=i) for i in range((end_date-start_date).days+1)]

In [30]:
  recheader.extend(datevals)

In [31]:
 gpframe=gpd.GeoDataFrame(data,geometry=gpd.points_from_xy(data.lon, data.lat))

In [32]:
gpframe.crs={'init': 'epsg:4326'}
gpframe=gpframe.to_crs({'init': 'epsg:26917'})
data['x']=[geom.x for geom in gpframe.geometry]
data['y']=[geom.y for geom in gpframe.geometry]

In [34]:
data=data.drop(columns=['geometry'])


In [36]:

    xy=data[['x','y']].values
  

In [37]:
xy


array([[ 447849.08788542, 4591044.05954433],
       [ 432602.94750043, 4592342.90169444],
       [ 456009.54450162, 4598312.56492716],
       ...,
       [ 455400.30244077, 4521919.84295097],
       [ 592802.50690859, 2937230.42149944],
       [ 436044.74097307, 4575752.3308105 ]])

In [38]:

    latlon=data[['lon','lat']].values


In [39]:
latlon

array([[-81.624544,  41.469299],
       [-81.807257,  41.479861],
       [-81.527352,  41.535256],
       ...,
       [-81.529086,  40.847111],
       [-80.068317,  26.55269 ],
       [-81.764283,  41.330715]])

In [40]:

    dates=data['Date'].values

In [41]:
dates

array([datetime.date(2020, 4, 29), datetime.date(2020, 5, 17),
       datetime.date(2020, 6, 25), ..., datetime.date(2020, 3, 26),
       datetime.date(2020, 4, 19), datetime.date(2020, 5, 25)],
      dtype=object)

In [42]:
 clusterData=pd.DataFrame(columns=recheader)

In [43]:
  clustering = DBSCAN(eps=100, min_samples=2,algorithm='kd_tree').fit(xy)

In [44]:
labels = clustering.labels_
total_clusters = len(set(labels))
k=0
geometries=[]
ids=[]

In [45]:
labels

array([-1, -1, -1, ..., -1, -1, 36], dtype=int64)

In [46]:
total_clusters

176

In [46]:
for i in range(total_clusters):
        ltln=latlon[labels==i]
        date=dates[labels==i]
        prjpoints=xy[labels==i]
        if len(ltln)!=0 and len(ltln)>=minneighbors:
            tdframe=pd.DataFrame(columns=['date'])
            tdframe.date=datevals
            newdframe=pd.DataFrame(columns=['date','counts'])
            #aggregate counts based on date
            unique, counts = np.unique(Date, return_counts=True)
            newdframe.date=unique
            newdframe.counts=counts
            tdframe=tdframe.merge(newdframe,on='Date',how='outer')
            tdframe=tdframe.fillna(0)
            #cumulative sum for the dates
            cnts=np.cumsum(tdframe.counts.values)
            #set zero for total neighbors
            cnts[cnts<minneighbors]=0
            tdframe.counts=cnts
            #for generating centroids
            geom=MultiPoint(ltln)
            dat=[k,geom.centroid.x,geom.centroid.y]
            ids.append(k)
            geom_proj=MultiPoint(prjpoints)
            #convex hulls based on all members
            geom_hull=geom_proj.convex_hull
            if geom_hull.geom_type!='Polygon':
                geom_hull=geom_hull.buffer(maxdistance)
            geometries.append(geom_hull)
            dat.extend(tdframe.counts.values.tolist())
            clusterData.loc[len(clusterData)]=dat
            k+=1

NameError: name 'Date' is not defined

In [41]:
minneighbors=2

In [47]:
for i in range(total_clusters):
        ltln=latlon[labels==i]
        date=dates[labels==i]
        prjpoints=xy[labels==i]

In [48]:
if len(ltln)!=0 and len(ltln)>=minneighbors:
            tdframe=pd.DataFrame(columns=['date'])
            tdframe.date=datevals
            newdframe=pd.DataFrame(columns=['date','counts'])

In [52]:
unique, counts = np.unique(date, return_counts=True)
newdframe.date=unique
newdframe.counts=counts
tdframe=tdframe.merge(newdframe,on='date',how='outer')

In [53]:
tdframe=tdframe.fillna(0)

In [54]:
tdframe

date  counts
0    2019-04-06     0.0
1    2019-04-07     0.0
2    2019-04-08     0.0
3    2019-04-09     0.0
4    2019-04-10     0.0
5    2019-04-11     0.0
6    2019-04-12     0.0
7    2019-04-13     0.0
8    2019-04-14     0.0
9    2019-04-15     0.0
10   2019-04-16     0.0
11   2019-04-17     0.0
12   2019-04-18     0.0
13   2019-04-19     0.0
14   2019-04-20     0.0
15   2019-04-21     0.0
16   2019-04-22     0.0
17   2019-04-23     0.0
18   2019-04-24     0.0
19   2019-04-25     0.0
20   2019-04-26     0.0
21   2019-04-27     0.0
22   2019-04-28     0.0
23   2019-04-29     0.0
24   2019-04-30     0.0
25   2019-05-01     0.0
26   2019-05-02     0.0
27   2019-05-03     0.0
28   2019-05-04     0.0
29   2019-05-05     0.0
..          ...     ...
438  2020-06-17     0.0
439  2020-06-18     0.0
440  2020-06-19     0.0
441  2020-06-20     0.0
442  2020-06-21     0.0
443  2020-06-22     0.0
444  2020-06-23     0.0
445  2020-06-24     0.0
446  2020-06-25     0.0
447  2020-06-26     0.0
448  2020-06-27     0.0
449  2020-06-28     0.0
450  2020-06-29     0.0
451  2020-06-30     0.0
452  2020-07-01     0.0
453  2020-07-02     0.0
454  2020-07-03     0.0
455  2020-07-04     0.0
456  2020-07-05     0.0
457  2020-07-06     0.0
458  2020-07-07     0.0
459  2020-07-08     0.0
460  2020-07-09     0.0
461  2020-07-10     0.0
462  2020-07-11     0.0
463  2020-07-12     0.0
464  2020-07-13     0.0
465  2020-07-14     0.0
466  2020-07-15     0.0
467  2020-07-16     0.0

[468 rows x 2 columns]

In [60]:
cnts=0
    

In [61]:
tdframe.counts=cnts

In [63]:
geom=MultiPoint(ltln)
           

In [64]:
geom

In [66]:

            dat=[k,geom.centroid.x,geom.centroid.y]
          

IndexError: list index out of range